services:
  # --- 1. Base de Données (Portable) ---
  postgres_db:
    image: postgres:15-alpine
    container_name: chess_db_portable
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: jr_bot
      POSTGRES_PASSWORD: fish_bot1800
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd_used.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chess-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jr_bot -d bot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- 2. Backend Java ---
  jr-bot:
    build: ./jr-bot
    container_name: chess_backend
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/bot_db?currentSchema=chess_bot
      SPRING_DATASOURCE_USERNAME: jr_bot
      SPRING_DATASOURCE_PASSWORD: fish_bot1800
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - chess-network

  # --- 3. Module IA Python ---
  ai-engine:
    build: ./python_files
    container_name: chess_ai
    environment:
      BACKEND_URL: http://jr-bot:8082/api
      DB_HOST: postgres_db
      DB_NAME: bot_db
      DB_USER: jr_bot
      DB_PASS: fish_bot1800
      DB_SCHEMA: chess_bot
    depends_on:
      - jr-bot
    networks:
      - chess-network

volumes:
  postgres_data:

networks:
  chess-network:
    driver: bridge