pipeline {
    agent any

    tools {
        maven 'maven' 
        jdk 'jdk21'
    }

    stages {
        stage('Compilation') {
            steps {
                dir('jr-bot') {
                    sh 'mvn clean compile -B'
                }
            }
        }

        stage('Tests Unitaires') {
            steps {
                dir('jr-bot') {
                    echo '=== 🧪 Lancement des Tests ==='
                    sh 'mvn test -B'
                }
            }
        }

        stage('Build JAR') {
            steps {
                dir('jr-bot') {
                    echo '===  Création du fichier JAR ==='
                    sh 'mvn package -DskipTests -B'
                }
            }
        }
    }

    post {
        always {
            junit 'jr-bot/target/surefire-reports/*.xml'
        }
        success {
            echo 'SUCCÈS : Le JRRZF Bot est compilé et testé !'
        }
        failure {
            echo 'ÉCHEC : Un test a planté ou la compilation a échoué.'
        }
    }
}